apiVersion: apps/v1
kind: Deployment
metadata:
  name: aigc-web
  labels:
    app: aigc-web
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: aigc-web
  template:
    metadata:
      labels:
        app: aigc-web
    spec:
      containers:
        - name: aigc-web
          image: ${GITEE_DOCKER_IMAGE}
          imagePullPolicy: IfNotPresent
          env:
            - name: ilogtail
              value: "true"
          ports:
            - containerPort: 80
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          volumeMounts:
            - name: timezone
              mountPath: /etc/localtime
      imagePullSecrets:
        - name: ee
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai

---

apiVersion: v1
kind: Service
metadata:
 name: aigc-web-svc
spec:
 type: ClusterIP # 服务类型
 ports:
   - port: 80
     targetPort: 80
 selector:
   app: aigc-web

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: aigc-web-hpa-c
  labels:
    app: aigc-web-hpa-c
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aigc-web
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: aigc-web-hpa-m
  labels:
    app: aigc-web-hpa-m
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aigc-web
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 80

